AllCops:
  NewCops: enable

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
