source "https://rubygems.org"

gem "guard", "~> 2.19"
gem "guard-rake", "~> 1.0"
gem "minitest", "~> 6.0"
gem "parser", "~> 3.3.10"
gem "rake", "~> 13.0"
gem "reline", "~> 0.6"
gem "standard", "~> 1.52.0", require: false
gem "wordexp", "~> 0.2"
